config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/forward_message', to: 'home#forward_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def forward_message
    if params[:name].empty? || params[:email].empty? || params[:message].empty?
      return redirect_to root_path, alert: 'Please fill all values'
    end

    message_data = {
      form: {
        name: params[:name],
        email: params[:email],
        message: params[:message]
      }
    }

    url = 'https://monroneylabels.com/pages/dealer_message.json'

    response = RestClient.post url, message_data

    return redirect_to root_path, notice: 'Message sent successfully' if response.code == 200

    redirect_to root_path, alert: 'Some error occured'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row justify-content-center align-items-center " style="min-height: 80vh">
  <div class="col-6  border p-4">
    <p class="lead">Send a message to the MonroneyLabels team</p>
    <%= form_with url: forward_message_path do |f| %>
      <div class="row mb-4">
        <%= f.label :name, class: 'col-2 col-form-label'%>
        <div class="col-10">
          <div class="input-group">
            <span class="input-group-text">
              <i class="bi bi-person-circle"></i>
            </span>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="row mb-4">
        <%= f.label :email, class: 'col-2 col-form-label'%>
        <div class="col-10">
          <div class="input-group">
            <span class="input-group-text">
              <i class="bi bi-envelope"></i>
            </span>
            <%= f.email_field :email, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="row mb-4">
        <%= f.label :message, class: 'col-2 col-form-label'%>
        <div class="col-10">
          <%= f.text_area :message, class: 'form-control'%>
        </div>
      </div>

      <div class="row-mt2">
        <div class="col mx-auto">
          <%= f.submit "Send Message!", class:"btn btn-warning"%>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<%end%>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessagingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container-fluid mt-5">
      <div class="container">
        <%= render partial: "layouts/notifications" %>
      </div>

        <%= yield %>
    </div>
  </body>
</html>